### PR TITLE
Add depth option, defaulting to 1

### PR DESCRIPTION
**Pull request by vweevers**

### CODE REVIEW

**Comment by feross** [comment]
I like this change, thanks for the PR! Can we use `Infinity` instead of `-1` to represent an infinite depth? That seems less magical to me. Lmk what you think!

**Comment by vweevers** [comment]
> Can we use `Infinity` instead of `-1` to represent an infinite depth?

I don't mind.

How should we handle `0`, if at all? Currently that means the same as `-1`. We can let git throw (as it doesn't accept `--depth=0`) or reject `<= 0` ourselves with a friendlier message before we spawn git.

**Comment by feross** [comment]
> How should we handle 0, if at all? 

I like the idea of rejecting ourselves with a friendly message :)

**Comment by feross** [comment]
1.3.0

**Pull request merged**
